x-aws-creds: &aws_creds
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID-dummy}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY-dummy}
  AWS_PREFIX: ${AWS_PREFIX-dummy}

services:
  wordpress:
    image: wordpress:6.4.3
    ports:
      - '666:80'
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-wp-content:/var/www/html/wp-content
    depends_on:
      - wordpress-db
    restart: unless-stopped

  wordpress-db:
    image: mariadb:10.3.39
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: unless-stopped

  load-balancer:
    build:
      context: ./apps/load-balancer
      dockerfile: Dockerfile
    ports:
      - '8808:80'
      - '8800:8800'
    volumes:
      - ./apps/lookpay-api:/lookpay-api
      - ./apps/lookpay-api/storage/logs:/usr/local/openresty/nginx/logs
      - ./apps/med-api:/med-api
    depends_on:
      - lookpay-api
      - med-api
    restart: unless-stopped

  lookpay-api:
    build:
      context: ./apps/lookpay-api
      dockerfile: Dockerfile.development
    environment:
      <<: *aws_creds
    volumes:
      - ./apps/lookpay-api:/lookpay-api
      - ./apps/lookpay-api/fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./shared:/var/lib/shared
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  med-api:
    build:
      context: ./apps/med-api
      dockerfile: Dockerfile.development
    environment:
      <<: *aws_creds
    volumes:
      - ./apps/med-api:/med-api
      - ./shared:/var/lib/shared
    restart: unless-stopped

  adm-api:
    build:
      context: ./apps/adm-api
      dockerfile: Dockerfile.development
    environment:
      <<: *aws_creds
    ports:
      - '8008:80'
    volumes:
      - ./apps/adm-api:/var/www/html/app
      - ./shared:/var/lib/shared
    depends_on:
      - elasticmq
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  elasticmq:
    image: softwaremill/elasticmq:1.5.7
    ports:
      - '9325:9325'
      - '9324:9324'
    volumes:
      - ./apps/elasticmq/queues.conf:/opt/elasticmq.conf
    restart: unless-stopped

  redis:
    image: redis:7.0.8-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped

  database:
    image: mariadb:10.4.30
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      TZ: America/Sao_Paulo
    restart: unless-stopped

volumes:
  wordpress-db:
  wordpress-wp-content:
  database_data:
