FROM node:18.20.4-alpine

WORKDIR /app

CMD yarn install --frozen-lockfile \
  && cd apps/storybook-native/src/packages  \
  && yarn && cd ../../../../ \
  && cd apps/storybook-web/src/packages  \
  && yarn && cd ../../../../
