services:
  shared74:
    build:
      context: ./shared
      dockerfile: Dockerfile.php74

  shared83:
    build:
      context: ./shared
      dockerfile: Dockerfile.php83

  adm-api:
    build:
      context: ./apps/adm-api
      args:
        COMPOSER_OPTS: ''
    entrypoint: sh
    command:
      - -c
      - 'vendor/bin/phpunit test/unit --testdox --colors'

  load-balancer:
    image: ghcr.io/lunarmodules/busted:v2.2.0
    platform: linux/amd64
    volumes:
      - './apps/load-balancer:/data'
    command: .

  lookpay-api:
    build:
      context: ./apps/lookpay-api
      dockerfile: Dockerfile
      args:
        COMPOSER_OPTS: ''
    entrypoint: sh
    command:
      - -c
      - 'vendor/bin/phpunit tests --testdox --colors --migrate-configuration'

  wc-lookpay-credit-card:
    image: stephenneal/php-composer:7.4-v2
    volumes:
      - './apps/wc-lookpay-credit-card:/app'
    entrypoint: sh
    working_dir: /app
    user: root
    command:
      - -c
      - 'composer install && vendor/bin/phpunit tests --testdox --colors'
