FROM node:18.20.4-alpine

WORKDIR /app

CMD yarn install --frozen-lockfile \
  && cd apps/storybook-native/src/packages && yarn install --frozen-lockfile\
  && cd ../../../../ \
  && cd apps/storybook-web/src/packages && yarn install --frozen-lockfile\
  && cd ../../../../ \
  && yarn workspace @monorepo/storybook-web jest \
  && yarn workspace @monorepo/storybook-native jest --updateSnapshot
