version: '3.8'

services:
  test-pdo-cast-adm-api-integration:
    build:
      context: ./shared/pdo-cast/
    entrypoint: sh
    command:
      - -c
      - 'composer install && vendor/bin/phpunit tests --testdox --colors'

  test-adm-api:
    build:
      context: ./apps/adm-api
      dockerfile: Dockerfile.cli
      args:
        COMPOSER_OPTS: ''
    volumes:
      - ./apps/adm-api:/app
    entrypoint: sh
    command:
      - -c
      - 'vendor/bin/phpunit test/unit --testdox --colors'

  test-load-balancer:
    image: ghcr.io/lunarmodules/busted:v2.2.0
    volumes:
      - './apps/load-balancer:/data'
    command: .

  test-lookpay-api:
    build:
      context: ./apps/lookpay-api
      dockerfile: Dockerfile
      args:
        COMPOSER_OPTS: ''
    volumes:
      - ./apps/lookpay-api:/lookpay-api
    entrypoint: sh
    command:
      - -c
      - 'vendor/bin/phpunit tests --testdox --colors'

  test-wc-lookpay-credit-card:
    image: stephenneal/php-composer:7.4-v2
    volumes:
      - './apps/wc-lookpay-credit-card:/app'
    entrypoint: sh
    working_dir: /app
    user: root
    command:
      - -c
      - 'composer install && vendor/bin/phpunit tests --testdox --colors'
