version: '3.8'

services:
  pdo-cast-adm-api-integration:
    build: ./shared/pdo-cast/
    entrypoint: sh
    command:
      - -c
      - 'composer install && vendor/bin/phpunit tests --testdox --colors'
  adm-api:
    build: ./apps/adm-api
    volumes:
      - ./apps/adm-api:/app
      - ./shared:/var/shared
    entrypoint: sh
    command:
      - -c
      - 'composer install && vendor/bin/phpunit test --testdox --colors'

  load-balancer:
    image: ghcr.io/lunarmodules/busted:v2.2.0
    volumes:
      - './apps/load-balancer:/data'
    command: .
