version: '3.8'

services:
  pdo-cast-adm-api-integration:
    build:
      context: ./apps/adm-api
    volumes:
      - './shared/pdo-cast:/var/www/html/app'
    entrypoint: sh
    tty: true
    command:
      - -c
      - 'composer update && vendor/bin/phpunit tests --testdox --colors'

  pdo-cast-lookpay-api-integration:
    build:
      context: ./apps/lookpay-api
    volumes:
      - './shared/pdo-cast:/var/shared/pdo-cast/'
    entrypoint: sh
    tty: true
    working_dir: /var/shared/pdo-cast/
    command:
      - -c
      - 'composer install && composer update && vendor/bin/phpunit tests --testdox --colors'

  adm-api:
    build:
      context: ./apps/adm-api
      args:
        COMPOSER_OPTS: ''
    entrypoint: sh
    tty: true
    command:
      - -c
      - 'vendor/bin/phpunit test/unit --testdox --colors'

  load-balancer:
    image: ghcr.io/lunarmodules/busted:v2.2.0
    tty: true
    volumes:
      - './apps/load-balancer:/data'
    command: .

  lookpay-api:
    build:
      context: ./apps/lookpay-api
      dockerfile: Dockerfile
      args:
        COMPOSER_OPTS: ''
    entrypoint: sh
    tty: true
    command:
      - -c
      - 'vendor/bin/phpunit tests --testdox --colors'

  wc-lookpay-credit-card:
    image: stephenneal/php-composer:7.4-v2
    volumes:
      - './apps/wc-lookpay-credit-card:/app'
    entrypoint: sh
    tty: true
    working_dir: /app
    user: root
    command:
      - -c
      - 'composer install && vendor/bin/phpunit tests --testdox --colors'
