x-laravel-default-envs: &laravel_default_envs
  ADM_API_URL: ${ADM_API_URL}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID-dummy}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION-dummy}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY-dummy}
  DB_CONNECTION: ${DB_CONNECTION}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}
  REDIS_CACHE_DB: ${REDIS_CACHE_DB}
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  REDIS_USERNAME: ${REDIS_USERNAME}

x-adm-api-envs: &adm_api_envs
  MED_DB_DATABASE: ${MED_DB_DATABASE}
  MED_APP_AUTH_TOKEN: ${MED_APP_AUTH_TOKEN}
  REPLICADOR_DB_USERNAME: ${ADM_REPLICADOR_DB_USERNAME}
  REPLICADOR_DB_PASSWORD: ${ADM_REPLICADOR_DB_PASSWORD}
  <<: *laravel_default_envs

x-lookpay-api-envs: &lookpay_api_envs
  APP_NAME: ${LP_APP_NAME}
  APP_ENV: ${LP_APP_ENV}
  APP_KEY: ${LP_APP_KEY}
  APP_DEBUG: ${LP_APP_DEBUG}
  APP_URL: ${LP_APP_URL}
  DB_DATABASE: ${LP_DB_DATABASE}
  IUGU_ACCOUNT_ID: ${LP_IUGU_ACCOUNT_ID}
  SECRET_MOBILE_STOCK_API_TOKEN: ${LP_SECRET_MOBILE_STOCK_API_TOKEN}
  <<: *laravel_default_envs

x-med-api-envs: &med_api_envs
  APP_NAME: ${MED_APP_NAME}
  APP_ENV: ${MED_APP_ENV}
  APP_KEY: ${MED_APP_KEY}
  APP_DEBUG: ${MED_APP_DEBUG}
  APP_URL: ${MED_APP_URL}
  APP_AUTH_TOKEN: ${MED_APP_AUTH_TOKEN}
  DB_DATABASE: ${MED_DB_DATABASE}
  DB_DATABASE_MOBILE_STOCK: ${ADM_DB_DATABASE}
  JWT_SECRET: ${MED_JWT_SECRET}
  <<: *laravel_default_envs

services:
  wordpress:
    image: wordpress:6.4.3
    ports:
      - '666:80'
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-wp-content:/var/www/html/wp-content
    depends_on:
      - wordpress-db
    restart: unless-stopped

  wordpress-db:
    image: mariadb:10.3.39
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: unless-stopped

  load-balancer:
    build:
      context: ./apps/load-balancer
      dockerfile: Dockerfile
    ports:
      - '8808:8808'
      - '8080:8080'
    volumes:
      - ./apps/lookpay-api:/lookpay-api
      - ./apps/lookpay-api/storage/logs:/usr/local/openresty/nginx/logs
      - ./apps/med-api:/med-api
      - ./apps/load-balancer/certs:/etc/letsencrypt
    depends_on:
      - lookpay-api
      - med-api
    restart: unless-stopped

  lookpay-api:
    build:
      context: ./apps/lookpay-api
      dockerfile: Dockerfile.development
    environment:
      <<: *lookpay_api_envs
    volumes:
      - ./apps/lookpay-api:/lookpay-api
      - ./apps/lookpay-api/config/php.ini-development:/usr/local/etc/php/php.ini
      - ./shared:/var/lib/shared
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  med-api:
    build:
      context: ./apps/med-api
      dockerfile: Dockerfile.development
    environment:
      <<: *med_api_envs
    volumes:
      - ./apps/med-api:/med-api
      - ./apps/med-api/config/php.ini-development:/usr/local/etc/php/php.ini
      - ./shared:/var/lib/shared
    restart: unless-stopped

  adm-api:
    build:
      context: ./apps/adm-api
      dockerfile: Dockerfile.development
    environment:
      <<: *adm_api_envs
    ports:
      - '8008:80'
    volumes:
      - ./apps/adm-api:/var/www/html/app
      - ./shared:/var/lib/shared
    depends_on:
      - elasticmq
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  elasticmq:
    image: softwaremill/elasticmq:1.5.7
    ports:
      - '9325:9325'
      - '9324:9324'
    volumes:
      - ./apps/elasticmq/queues.conf:/opt/elasticmq.conf
    restart: unless-stopped

  redis:
    image: redis:7.0.8-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped

  database:
    image: mariadb:10.4.30
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database_data:/var/lib/mysql
      - ./apps/database/my.cnf-development:/etc/mysql/my.cnf
    ports:
      - '3306:3306'
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      TZ: America/Sao_Paulo
    restart: unless-stopped

volumes:
  wordpress-db:
  wordpress-wp-content:
  database_data:
