version: '3.8'

services:
  adm-api:
    image: backend_adm-api:latest
    volumes:
      - ./apps/adm-api:/app
  pdo-cast-adm-api-integration:
    image: backend_adm-api:latest
    volumes:
      - ./shared/pdo-cast:/app
    working_dir: /app
    command: composer install && vendor/bin/phpunit tests --testdox --colors

  load-balancer:
    image: ghcr.io/lunarmodules/busted:v2.2.0
    volumes:
      - './apps/load-balancer:/data'
    command: .
