version: '3.8'

services:
  pdo-cast-adm-api-integration:
    build: ./shared/pdo-cast
    working_dir: /app
    entrypoint: sh

    command:
      - -c
      - 'composer install && vendor/bin/phpunit tests --testdox --colors'
  adm-api:
    build: ./apps/adm-api
    volumes:
      - ./apps/adm-api:/app

      - ./shared:/var/shared
    depends_on:
      - pdo-cast-adm-api-integration

  load-balancer:
    image: ghcr.io/lunarmodules/busted:v2.2.0
    volumes:
      - './apps/load-balancer:/data'
    command: .
