services:
  shared74:
    build:
      context: ./shared
      dockerfile: Dockerfile.php74

  shared83:
    build:
      context: ./shared
      dockerfile: Dockerfile.php83

  adm-api:
    build:
      context: ./apps/adm-api
      args:
        COMPOSER_OPTS: ''
    entrypoint: sh
    command:
      - -c
      - 'vendor/bin/phpunit test/unit --testdox --colors'

  load-balancer:
    image: ghcr.io/lunarmodules/busted:v2.2.0
    platform: linux/amd64
    volumes:
      - './apps/load-balancer:/data'
    command: .

  lookpay-api:
    build:
      context: ./apps/lookpay-api
      dockerfile: Dockerfile
      args:
        COMPOSER_OPTS: ''
    entrypoint: sh
    command:
      - -c
      - 'vendor/bin/phpunit tests --testdox --colors'

  med-api:
    build:
      context: ./apps/med-api
      dockerfile: Dockerfile
      args:
        COMPOSER_OPTS: ''
    entrypoint: sh
    command:
      - -c
      - 'vendor/bin/phpunit tests --testdox --colors'

  wc-lookpay-credit-card:
    image: stephenneal/php-composer:7.4-v2
    volumes:
      - './apps/wc-lookpay-credit-card:/app'
    entrypoint: sh
    working_dir: /app
    user: root
    command:
      - -c
      - 'composer install && vendor/bin/phpunit tests --testdox --colors'

  storybook-web-test:
    image: node:18.20.4-alpine
    working_dir: /app
    volumes:
      - ./apps/storybook-web:/app
    command: >
      sh -c "yarn install --frozen-lockfile && cd apps/storybook-web/src/packages && yarn install && cd ../.. && yarn jest"
    tty: true
    stdin_open: true
    environment:
      - CI=true

  storybook-native-test:
    image: node:18.20.4-alpine
    working_dir: /app
    volumes:
      - ./apps/storybook-native:/app
    command: >
      sh -c "yarn install --frozen-lockfile && cd apps/storybook-native/src/packages && yarn install && cd ../.. && yarn jest --updateSnapshot"
    tty: true
    stdin_open: true
    environment:
      - CI=true
