x-aws-creds: &aws_creds
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

x-lookpay-api-envs: &lookpay_api_envs
  APP_NAME: ${LP_APP_NAME}
  APP_ENV: ${LP_APP_ENV}
  APP_KEY: ${LP_APP_KEY}
  APP_DEBUG: ${LP_APP_DEBUG}
  APP_URL: ${LP_APP_URL}
  DB_CONNECTION: ${LP_DB_CONNECTION}
  DB_HOST: ${LP_DB_HOST}
  DB_PORT: ${LP_DB_PORT}
  DB_DATABASE: ${LP_DB_DATABASE}
  DB_USERNAME: ${LP_DB_USERNAME}
  DB_PASSWORD: ${LP_DB_PASSWORD}
  IUGU_ACCOUNT_ID: ${LP_IUGU_ACCOUNT_ID}
  SECRET_MOBILE_STOCK_API_TOKEN: ${SECRET_MOBILE_STOCK_API_TOKEN}
  MOBILE_STOCK_API_URL: ${MOBILE_STOCK_API_URL}
  <<: *aws_creds

version: '3.8'

services:
  adm-api:
    image: ${CONTAINER_REGISTRY}adm-api:latest
    environment:
      <<: *aws_creds
    volumes:
      - '/var/efs/.env.php:/var/www/html/app/.env.php'
      - adm-logs:/var/www/html/app/log
      - /var/efs/certificados:/var/www/html/app/certificados
    ports:
      - '8008:80'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: any
      update_config:
        order: start-first

  load-balancer:
    image: ${CONTAINER_REGISTRY}load-balancer:latest
    ports:
      - '8808:80'
    volumes:
      - /var/efs/load-balancer-access.log:/usr/local/openresty/nginx/logs/server_access.log
    networks:
      net:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: any
      update_config:
        order: start-first

  lookpay-api:
    image: ${CONTAINER_REGISTRY}lookpay-api:latest
    environment:
      <<: *lookpay_api_envs
    networks:
      net:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: any
      update_config:
        order: start-first

  swarm-cronjob:
    image: crazymax/swarm-cronjob
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - 'TZ=America/Sao_Paulo'
      - 'LOG_LEVEL=info'
    deploy:
      placement:
        constraints:
          - node.role == manager

  'artisan-queue-worker':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'artisan', 'queue:work', '--tries=50000', '--backoff=90']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    environment:
      APP_LOG_LEVEL: emergency
      <<: *aws_creds
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      restart_policy:
        condition: any

  prune-nodes:
    image: docker
    command: ['docker', 'system', 'prune', '-a', '-f']
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      mode: global
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 */2 * * *'
      restart_policy:
        condition: none

  # ------------------------------------------------[JOBS]------------------------------------------------------------ #

  'atualiza-data-vencimento-correcoes':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobAtualizaDataVencimentoCorrecoes.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=30 1 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'pagamento-saques':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobPagamentoSaques.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=50 10,16,21,23 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'inteirar-pagamento-automatico':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobInteirarPagamentoAuto.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=40 9,15,23 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'atualiza-trocas':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobAtualizaTrocas.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 0 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'descontar-trocas-pontos':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobDescontarTrocasPonto.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=30 2 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'atualiza-quantidade-vendida':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobAtualizarQuantidadeVendida.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=15 0 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'cancelamento-automatico':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobCancelamentoAutomatico.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 2 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'separacao-atrasada':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobSeparacaoAtrasada.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=30 7 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'calcular-percentual-frete-pontos-coleta':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobCalcularPercentualFretePontosColeta.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=3 1 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'corta-pontos-ineficientes':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobCortaPontosIneficientes.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=50 3 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'limpa-historico-pesquisa-opensearch':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobLimpaHistoricoPesquisaOpensearch.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=10 0 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'separacao-pontos-coleta-agendada':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobAcompanhamentoAgendado.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=10 8,14 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'gerar-pontuacao-produtos':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobGerarPontuacaoProdutos.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=30 0 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'gerar-catalogo':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobGerarCatalogo.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 5-23 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'captura-fraudulentos-devolucoes':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobCapturaFraudulentosDevolucoes.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=45 3 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'gerar-reputacao-fornecedores':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobGerarReputacaoFornecedores.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 4 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'processamento-entrega-produto':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobProcessamentoEntregaProduto.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=10 4 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'atualizar-opensearch':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobAtualizarOpensearch.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=*/5 * * * *'
        - 'swarm.cronjob.skip-running=true'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0
      update_config:
        failure_action: continue

  'gerencia-logs-opensearch':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobGerenciaLogsOpensearch.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 * * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'insere-comissoes':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobInsereComissoes.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=40 0 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'forca-entrega':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobForcaEntrega.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 20 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'zera-subconta-iugu':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobSubConta.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=40 1 1 * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'cancela-transacoes-pendentes':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobCancelaTransacoesPendentes.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    environment:
      <<: *aws_creds
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=2 06-23,0 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'deleta-logs':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobDeletaLogs.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=32 4 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'verifica-erro-sistema':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobVerificaErroSistema.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 3 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'produtos-parados-estoque-fulfilment':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobNotificaEstoqueParado.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=30 8 1 * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'bloqueia-reposicao-fornecedor':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobBloquearFornecedor.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 5 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'limpa-localizacao-sem-estoque':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    environment:
      <<: *aws_creds
    command: ['php', 'src/jobs/jobLimparLocalizacaoEstoque.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=5 4 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'atualizar-telefone-nos-enderecos':
    image: ${CONTAINER_REGISTRY}adm-cli:latest
    command: ['php', 'src/jobs/jobAtualizarTelefoneNosEnderecos.php']
    volumes:
      - '/var/efs/.env.php:/app/.env.php'
      - 'adm-logs:/app/log'
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=30 5 * * *'
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      replicas: 0

  'lookpay-api-sync-with-mobile-stock':
    image: ${CONTAINER_REGISTRY}lookpay-api:latest
    command: ['php', 'artisan', 'app:sync-with-mobile-stock']
    environment:
      <<: *lookpay_api_envs
    deploy:
      labels:
        - 'swarm.cronjob.enable=true'
        - 'swarm.cronjob.schedule=0 17 * * *'
      resources:
        limits:
          cpus: '0.25'
          memory: 30M
      restart_policy:
        condition: on-failure

volumes:
  adm-logs:
    external: true

networks:
  net:
    driver: overlay
