package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'AutomatedTest'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("AutomatedTest")) {
    features {
        val feature1 = find<PullRequests> {
            pullRequests {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                provider = github {
                    authType = token {
                        token = "credentialsJSON:0187b8ea-ad9f-4227-a350-7558d85cb876"
                    }
                    filterTargetBranch = "+:refs/heads/main"
                    filterAuthorRole = PullRequests.GitHubRoleFilter.MEMBER
                }
            }
        }
        feature1.apply {
            vcsRootExtId = "Backend_AutomatedTestVcsRoot"
        }
    }
}
