package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            param("env.TELEGRAM_BOT_TOKEN", "6944709410:AAGBYdZmRhWfSM1nNoDp2rdVTHzFXof0Ilc")
        }
    }
}
