#!/usr/bin/env php
<?php

use MobileStock\helper\ConsoleKernel;

define('LARAVEL_START', microtime(true));

require __DIR__ . '/vendor/autoload.php';

$kernel = app(ConsoleKernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput(),
    new Symfony\Component\Console\Output\ConsoleOutput()
);

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
|
| Once Artisan has finished running, we will fire off the shutdown events
| so that any final work may be done by the application before we shut
| down the process. This is the last thing to happen to the request.
|
*/

$kernel->terminate($input, $status);

exit($status);

