ALTER TABLE produtos ADD COLUMN tag ENUM('TRADICIONAL', 'MODA') NOT NULL DEFAULT 'TRADICIONAL';
ALTER TABLE catalogo_fixo MODIFY COLUMN tipo ENUM(
    'IMPULSIONAR', 
    'MELHOR_FABRICANTE', 
    'PROMOCAO_TEMPORARIA', 
    'VENDA_RECENTE', 
    'MELHOR_PONTUACAO', 
    'TAG_GERAL', 
    'TAG_20',
    'TAG_40',
    'TAG_60',
    'TAG_80',
    'TAG_100'
    );
ALTER TABLE colaboradores ADD COLUMN tag_porcentagem TINYINT NOT NULL DEFAULT 0;
UPDATE produtos SET tag = 'MODA' WHERE produtos.id_fornecedor IN (12, 6984);
