name: Ci

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - synchronize
    workflow_dispatch:

jobs:
  ci:
    if: ${{ github.event.label.name == 'CI' }} || ${{ toJSON(github.event.pull_request.labels) }} | grep 'CI'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: CI
        run: docker-compose -f docker-compose.ci.yml up --build --abort-on-container-exit