name: Ci

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - synchronize
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: teste
        run: echo ${{ toJSON(github) }}

  ci:
    if: ${{ github.event.label.name == 'CI' || github.pull_request.labels.*.name == 'CI' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: CI
        run: docker-compose -f docker-compose.ci.yml up --build --abort-on-container-exit