name: test

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
    workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.label.name == 'CI' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: test

        run: pwd && ls && docker-compose -f docker-compose.ci.yml up --build --abort-on-container-exit