name: test

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
    workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.label.name == 'CI' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}
      - name: "set/get cache build"
        continue-on-error: true
        uses: satackey/action-docker-layer-caching@v0.0.11
      - name: test
        run: docker-compose -f docker-compose.ci.yml up --abort-on-container-exit