name: test

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
    workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.label.name == 'CI' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}
      - name: 'set/get cache build'
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: docker-build-cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'build'
        run: mkdir -p /tmp/.buildx-cache && docker buildx build -f Dockerfile.test --cache-to type=local,dest=/tmp/.buildx-cache apps/adm-api
      - name: test
        run: docker-compose -f docker-compose.ci.yml up --build --abort-on-container-exit
