name: test

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
    workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.label.name == 'TEST' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}
      # - name: 'set/get cache build'
      #   uses: actions/cache@v4
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: docker-build-cache-PR${{ github.event.pull_request.number }}
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-cache-${{ runner.os }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: 'build'
      #   run: mkdir -p /tmp/.buildx-cache && cd apps/adm-api && docker buildx build --load -f Dockerfile.test -t backend_adm-api:latest --cache-to type=local,dest=/tmp/.buildx-cache --cache-from type=local,src=/tmp/.buildx-cache .
      - name: test
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
